# AI Tips for Faculty

## February 28, 2026

1.  If you ask AI to build a slide deck in Beamer, ask it to then generate images of individual slides from the pdf and review them for formatting issues.  It can detect overflows from the logs, but it needs to generate images (e.g., pngs) of the slides in order to see other formatting issues (spacing between elements, etc.).

2.  Claude Code (and Gemini CLI and OpenAI Codex) is a universal agent.  All you have to do is add instructions/rules/Python scripts/MCP connectors or whatever in Claude.md, Claude skills, or Claude plugins.  Then just tell Claude to do things, and it will consult the instructions, etc. 

    Skills are just text files.  A key thing about skills is that Claude only reads them when needed, so they don't clog up the context window.  You can tell Claude to use them with a slash command (/skill_name), or you can describe the skill in the Claude.md file (another text file that Claude always reads on startup), so Claude will use the skill when appropriate without being prompted by a slash command.

    You can easily create a Beamer skill.  Ask Claude to do it for you.  Give it your preferences for theme and styling.  You can  add rules like: 'no more than 5 seconds to read,' 'no more than 3 bullet points,' or whatever. Tell it that it should generate slide images whenever it creates a deck and review them for formatting.  Or split the tasks if you don't always need image generation: maybe beamer-create and beamer-review.

## March 7, 2026

If you have an AI CLI tool (Claude Code, OpenAI Codex, Gemini CLI), lots of possibilities open up.  For example, it can search your hard drive to find files with only vague clues - e.g., "I have a docx file somewhere in my dropbox folder that discusses ...  Find it."

If you use git, then you can also search the past.  Ask Claude to install git, then ask it to initialize a folder as a git repo and commit it.  Periodically, tell it "commit changes."  Each time it commits, it is creating a snapshot of the folder.  Later, you can say "I used to have a version of this file with a paragraph that discussed ...  Find the paragraph."  Git is great but a bit complex.  Fortunately, AI knows all about it, so we don't need to know anything.

Asking Claude to search past commits is much easier than searching manually through old Dropbox or Overleaf versions.  You can also ask AI to push to GitHub if you want a remote backup - or if you want to share files or create websites using GitHub Pages, etc.

## March 14, 2026

1. Last fall, Google gave NotebookLM the ability to generate slide decks.  Last month, Google added the ability to edit individual slides.  If you've played around with image generation, you know the drill: ask for one thing to be fixed, and AI makes unwanted changes to two other features in the process.  It's the same with NotebookLM slides.  Being able to make changes to one slide at a time reduces the pain, but it is still too painful to work with, IMO, though it does produce some interesting slides.  This [PDF](m1-ai-in-finance.pdf) is a Beamer deck I gave NotebookLM, and this [PPTX](m1-ai-in-finance.pptx) is NotebookLM's version (second version, actually - after I told NotebookLM to tone down its first version).

   Claude Code created the Beamer deck for me, using the autonomous "write, compile, generate PNG, read and edit, repeat" procedure I described in an earlier email.  I asked Claude if it could make the Beamer deck more visually appealing, and it chose to work with Quarto, which produces reveal.js HTML slides.  I've created those myself in the past.  Quarto is a Markdown language, similar in spirit to TeX (and accepts TeX math notation), but it is simpler than TeX and at the same time more versatile - produces websites, online books, can run embedded code to generate visualizations inline, etc.  Claude can also use Python to produce PowerPoint decks, but Claude said the output and process would be much better with Quarto.  Here is [Claude's output](https://mgmt675.kerryback.com/slides/m1-ai-in-finance.html). I think it is an improvement over Beamer and was relatively painless.

   To use this process effectively, you need to add an MCP connector for a browser tool to your Claude setup.  Claude can do that for you.  Then Claude can view the deck itself and make adjustments without prompting.  As with Beamer, I told Claude to produce a deck, view and assess, edit the deck, and repeat the process until Claude was happy with the result.

   A possible downside of HTML slide decks is that students may be unable to write notes on them.  This is solved by enabling Hypothesis in Quarto (ask Claude).  When you click the icon at the top right of the slides, you are prompted to sign in to your Hypothesis account (accounts are free).  Once you've done so, you can annotate the deck just as you would annotate a PDF in Acrobat.  When you return to the website (i.e., slide deck) and log back into Hypothesis, your annotations are visible.  Apparently, Hypothesis stores a copy of the website with annotations and then serves that copy when you log in.

2. If you haven't already tried MCP connectors for mail and calendar apps, then you might want to give it a shot.  I have two Gmail accounts and associated calendars (Rice and personal), and Rice's security policy makes merging them difficult.  But the security policy doesn't restrict API access, so Claude can use them for me.  Go figure.

   Claude walked me through setting up Google's MCP connectors.  Now, I can say, "Are there any events in my emails that should be added to my calendars?  If so, add them", "Are there any emails that I need to reply to?",  "Draft an email to ... about ... saying ..."

3. You can also ask Claude to keep a task list for you.  Tell it to create a task skill that stores your tasks in categories like personal, teaching, or research.  Then, you can ask, "What are my open teaching tasks?",  "Add a task to do ..."  Obviously, there are many to-do-list apps, and they are easy enough to use, but it simplifies things to reduce the number of apps I use and do everything inside Claude Code (the way all of personal computing will soon be, I think).

4. Along the same lines, Canvas has an API.  You have to click through Canvas and find a link to request an API key from some staff person (Claude can tell you how).  Once you have the key, you don't need to SSO login and two-factor authenticate anymore.
Claude can upload files and assignments, download assignment submissions, upload the gradebook and comments, and, of course, help with grading. Ask for a complete summary of why Claude assigned the grades it did, and use that as a starting point for your grading.  

   To be FERPA-compliant, ask for a script to upload a dummy gradebook and then run the script on the actual gradebook.  Obviously, you should also anonymize assignments before asking Claude to grade them. 
