### Working Papers

Back, K., Carlin, B., Kazempour, S. M., and C. Xie, 2023, [American Disclosure Options](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4648459).

Back, K., Celebi, O., Kakhbod, A., and A. M. Reppen, 2023, [Segmented Trading Markets](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4119978)

Back, K., Cocquemas, F., Ekren, I., and A. Lioui, 2021, [Optimal Transport and Risk Aversion in Kyle's Model of Informed Trading.](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3628726)

### Recent Publications

Back, K., Crotty, K., and S. M. Kazempour, 2022, [Validity, Tightness, and Forecasting Power of Risk Premium Bounds,](pubs/Back_Crotty_Kazempour_JFE_2022.pdf) *Journal of Financial Economics*, **144**, 732--760.

Back, K., and P. Barton, 2022, [Mediation and Strategic Delay in Bargaining and Markets,](https://www.sciencedirect.com/science/article/abs/pii/S0165188922000811) *Journal of Economic Dynamics and Control*, **141**.

Back, K., Liu, R., and A. Teguia, 2020, [Signaling in OTC Markets: Benefits and Costs of Transparency,](pubs/Back_Liu_Teguia_JFQA_2020.pdf) *Journal of Financial and Quantitative Analysis*, **55**, 47--75.

Back, K., Liu, R., and A. Teguia, 2019, [Increasing Risk Aversion and Life-Cycle Investing](pubs/Back_Liu_Teguia_MAFE_2019.pdf) *Mathematics and Financial Economics*, **13**, 287--302.

Back, K., Collin-Dufresne, P., Fos, V., Li, T., and A. Ljungqvist, 2018, [Activism, Strategic Trading, and Liquidity,](pubs/Back_et_al_Econometrica_2018.pdf) *Econometrica*, **86**, 1431--1463.

Back, K., Crane, A., and K. Crotty, 2018, [Skewness Consequences of Seeking Alpha,](pubs/Back_Crane_Crotty_RFS_2018.pdf) *Review of Financial Studies*, **31**, 4720--4761.

Back, K., Crotty, K., and T. Li, 2018, [Identifying Information Asymmetry in Securities Markets,](pubs/Back_Crotty_Li_RFS_2018.pdf) *Review of Financial Studies*, **31**, 2277--2325.

Back, K., and K. Crotty, 2015, [The Informational Role of Stock and Bond Volume,](pubs/Back_Crotty_RFS_2015.pdf) *Review of Financial Studies*, **28**, 1381--1427.

Back, K., 2014, [A Characterization of the Coskewness-Cokurtosis Pricing Model](Back_EconLetters_2014.pdf) *Economics Letters* **125**, 219--222. 

Back, K., and S. Baruch, 2013, [Strategic Liquidity Provision in Limit Order Markets,](pubs/Back_Baruch_Econometrica_2013.pdf) *Econometrica*, **81**, 363--392.
 


